#!/usr/bin/env bash
# displays string with a sleep 2 in between each iteration and dif string when receiving a SIGTERM signal
counter=1
trap func SIGTERM
function func() {
	echo "I am invincible!!!"
}
while [ $counter -eq 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
